name: Unit tests

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Api/TeslaRent.Application.UnitTests

      - name: Build
        run: dotnet build --no-restore
        working-directory: ./Api/TeslaRent.Application.UnitTests
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./Api/TeslaRent.Application.UnitTests

